---
title: "Reproducible documents"
author: "Anne G Jensen"
format: html
---

## Basics of R

```{r}
1 + 1
```

## Setup code chunk
```{r setup}
#| message: false
#| warning: false
library(tidyverse)
post_meal_data <- read_csv2(here::here("data/post-meal-insulin.csv"))
```

## Showing the data

```{r}
post_meal_data
```

```{r}
glimpse(post_meal_data)
```


?colnames


## About me 
- Anne Grosbol Jensen 
- Department of Clinical Biochemistry, AUH

**I** am a *medical* doctor during a PhD

## Simple code 
```{r}
3 * 3 
```

```{r}
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
  
```

```{r}
#| fig-cap: "Distribution of BMI"
#| label: fig-BMI-histogram
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
  
```


@fig-BMI-histogram


## Discrete plots
```{r}
#| fig-cap: "group"
#| label: fig-group-geombar
ggplot(post_meal_data, aes(x = Group)) +
  geom_bar()
```
According to @fig-group-geombar the groups... 

```{r}
#| fig-cap: "glykemi"
#| label: fig-glykemi-geombar
ggplot(post_meal_data, aes(x = glykemi)) +
  geom_bar()
```
According to the @fig-glykemi-geombar most of patients did not have glykemi.
